Repository ToriArtis/Do-Tori, pull requests merged in 2024-07, with the labels that each got.

#10 ♻️Refactor: Foldering
  client/.gitignore
  client/src/auth/api/Authapi.js
  client/src/auth/components/Auth.js
  client/src/auth/hooks/useAuth.js
  client/src/auth/models/Auth.js
  client/src/auth/viewmodels/AuthViewModels.js
  client/src/auth/views/AuthViews.js
  client/src/post/api/Postapi.js
  client/src/post/components/Post.js
  client/src/post/hooks/usePost.js
  client/src/post/models/Post.js
  client/src/post/viewmodels/PostViewModels.js
  client/src/post/views/PostViews.js
  client/src/todo/api/Todoapi.js
  client/src/todo/components/Todo.js
  client/src/todo/hooks/useTodo.js
  client/src/todo/models/Todo.js
  client/src/todo/viewmodels/TodoViewModels.js
  client/src/todo/views/TodoViews.js
Labels: ♻️Refactor, 🦦 김신이🦦

#11 ✨feat: Auth CRUD + JWT
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  Server/build.gradle
  Server/src/main/java/com/dotori/dotori/auth/config/ModelMapperConfig.java
  Server/src/main/java/com/dotori/dotori/auth/config/PasswordEncoderConfig.java
  Server/src/main/java/com/dotori/dotori/auth/config/SecurityConfig.java
  Server/src/main/java/com/dotori/dotori/auth/config/exception/BusinessLogicException.java
  Server/src/main/java/com/dotori/dotori/auth/config/exception/ExceptionCode.java
  Server/src/main/java/com/dotori/dotori/auth/controller/UserController.java
  Server/src/main/java/com/dotori/dotori/auth/dto/AuthSecurityDTO.java
  Server/src/main/java/com/dotori/dotori/auth/dto/LoginDTO.java
  Server/src/main/java/com/dotori/dotori/auth/dto/ResponseDTO.java
  Server/src/main/java/com/dotori/dotori/auth/dto/UserDTO.java
  Server/src/main/java/com/dotori/dotori/auth/entity/User.java
  Server/src/main/java/com/dotori/dotori/auth/entity/UserStatus.java
  Server/src/main/java/com/dotori/dotori/auth/jwt/JwtAuthenticationFilter.java
  Server/src/main/java/com/dotori/dotori/auth/jwt/TokenProvider.java
  Server/src/main/java/com/dotori/dotori/auth/repository/UserRepository.java
  Server/src/main/java/com/dotori/dotori/auth/service/CustomUserDetailsService.java
  Server/src/main/java/com/dotori/dotori/auth/service/UserInfoFilter.java
  Server/src/main/java/com/dotori/dotori/auth/service/UserService.java
  Server/src/main/java/com/dotori/dotori/config/CustomSecurityConfig.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostDTO.java
  Server/src/main/java/com/dotori/dotori/post/entity/Post.java
  Server/src/main/java/com/dotori/dotori/post/repository/PostRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
  Server/src/main/java/com/dotori/dotori/todo/dto/TodoDTO.java
  Server/src/main/java/com/dotori/dotori/todo/entity/Todo.java
  Server/src/main/java/com/dotori/dotori/todo/repository/TodoRepository.java
  Server/src/main/java/com/dotori/dotori/todo/service/TodoService.java
Labels: ✨Feat, 🔮 이소현🔮

#14 ♻️refactor: Oauth2 Refactor
  .idea/dataSources.xml
  Server/src/main/java/com/dotori/dotori/auth/config/OAuth2AuthenticationSuccessHandler.java
  Server/src/main/java/com/dotori/dotori/auth/config/SecurityConfig.java
  Server/src/main/java/com/dotori/dotori/auth/controller/OauthUserController.java
  Server/src/main/java/com/dotori/dotori/auth/entity/OAuthAttributes.java
  Server/src/main/java/com/dotori/dotori/auth/service/OAuth2Service.java
  Server/src/main/java/com/dotori/dotori/auth/service/Oauth2UserService.java
Labels: 👻Etc, ♻️Refactor, 🔮 이소현🔮

#15 🐛Fix: POST + TODO
  Server/src/main/java/com/dotori/dotori/auth/entity/User.java
  Server/src/main/java/com/dotori/dotori/config/RootConfig.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/CommentDTO.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostDTO.java
  Server/src/main/java/com/dotori/dotori/post/entity/Comment.java
  Server/src/main/java/com/dotori/dotori/post/entity/Post.java
  Server/src/main/java/com/dotori/dotori/post/repository/PostRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostSearchImpl.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
  Server/src/main/java/com/dotori/dotori/todo/dto/TodoDTO.java
  Server/src/main/java/com/dotori/dotori/todo/entity/Todo.java
  Server/src/main/java/com/dotori/dotori/todo/repository/TodoRepository.java
  Server/src/main/java/com/dotori/dotori/todo/service/TodoService.java
  Server/src/test/java/com/dotori/dotori/repository/AuthRepositoryTests.java
Labels: 🐛bug, 👻Etc, 🦦 김신이🦦, 💡Backend

#16 🐛 Fix : Follow error fix
  Server/src/main/java/com/dotori/dotori/Follow/controller/FollowController.java
  Server/src/main/java/com/dotori/dotori/auth/entity/User.java
Labels: 🐛bug, 🔮 이소현🔮, 💡Backend

#17 ✨Feat: Post Tag + Recomment + ThumbnailLimited + Bookmark
  Server/src/main/java/com/dotori/dotori/auth/entity/User.java
  Server/src/main/java/com/dotori/dotori/follow/controller/FollowController.java
  Server/src/main/java/com/dotori/dotori/follow/dto/FollowDTO.java
  Server/src/main/java/com/dotori/dotori/follow/entity/Follow.java
  Server/src/main/java/com/dotori/dotori/follow/repository/FollowRepository.java
  Server/src/main/java/com/dotori/dotori/follow/service/FollowService.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/CommentDTO.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostDTO.java
  Server/src/main/java/com/dotori/dotori/post/entity/Bookmark.java
  Server/src/main/java/com/dotori/dotori/post/entity/Comment.java
  Server/src/main/java/com/dotori/dotori/post/entity/Post.java
  Server/src/main/java/com/dotori/dotori/post/entity/Tag.java
  Server/src/main/java/com/dotori/dotori/post/repository/BookmarkRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/TagRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
  Server/src/main/java/com/dotori/dotori/todo/service/TodoService.java
Labels: 👻Etc, ✨Feat, 🧵Chore, 🦦 김신이🦦, 💡Backend

#19 🐛Fix: Search + CommentCount + ToriBoxCount, BookmarkCount + Boolean
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostListCommentCountDTO.java
  Server/src/main/java/com/dotori/dotori/post/repository/CommentRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/PostRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostSearchImpl.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 👻Etc, 🦦 김신이🦦, 💡Backend

#21 ✨Feat: MyPost + MyComment + MyFollowingPost + TagSearch
  Server/src/main/java/com/dotori/dotori/config/RootConfig.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/CommentDTO.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostListCommentCountDTO.java
  Server/src/main/java/com/dotori/dotori/post/entity/Comment.java
  Server/src/main/java/com/dotori/dotori/post/entity/Post.java
  Server/src/main/java/com/dotori/dotori/post/entity/Tag.java
  Server/src/main/java/com/dotori/dotori/post/repository/BookmarkRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/CommentRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/PostRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostLikeService.java
  Server/src/main/java/com/dotori/dotori/post/service/PostSearchImpl.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, ✨Feat, 🧵Chore, 🦦 김신이🦦, 💡Backend

#26 🐛 Fix : signup Fix
  client/app/_layout.tsx
  client/src/config/app-config.js
  client/src/user/api/userApi.js
  client/src/user/components/styles/signup_style.js
  client/src/user/models/User.js
Labels: 🐛bug, 🔮 이소현🔮, 💡Frontend

#27 ♻️ Refactor : auth
  .idea/dataSources.xml
  Server/src/main/java/com/dotori/dotori/auth/config/SecurityConfig.java
  Server/src/main/java/com/dotori/dotori/auth/controller/AuthController.java
  Server/src/main/java/com/dotori/dotori/auth/dto/AuthDTO.java
  Server/src/main/java/com/dotori/dotori/auth/entity/Auth.java
  Server/src/main/java/com/dotori/dotori/auth/entity/AuthStatus.java
  Server/src/main/java/com/dotori/dotori/auth/entity/UserStatus.java
  Server/src/main/java/com/dotori/dotori/auth/jwt/TokenProvider.java
  Server/src/main/java/com/dotori/dotori/auth/repository/AuthRepository.java
  Server/src/main/java/com/dotori/dotori/auth/service/AuthInfoFilter.java
  Server/src/main/java/com/dotori/dotori/auth/service/AuthService.java
  Server/src/main/java/com/dotori/dotori/auth/service/CustomAuthDetailsService.java
  Server/src/main/java/com/dotori/dotori/config/RootConfig.java
  Server/src/main/java/com/dotori/dotori/follow/controller/FollowController.java
  Server/src/main/java/com/dotori/dotori/follow/entity/Follow.java
  Server/src/main/java/com/dotori/dotori/follow/repository/FollowRepository.java
  Server/src/main/java/com/dotori/dotori/follow/service/FollowService.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/entity/Bookmark.java
  Server/src/main/java/com/dotori/dotori/post/entity/Comment.java
  Server/src/main/java/com/dotori/dotori/post/entity/Post.java
  Server/src/main/java/com/dotori/dotori/post/repository/BookmarkRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/CommentRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/PostRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostLikeService.java
  Server/src/main/java/com/dotori/dotori/post/service/PostSearchImpl.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
  Server/src/main/java/com/dotori/dotori/todo/entity/Todo.java
  Server/src/main/java/com/dotori/dotori/todo/repository/TodoRepository.java
  Server/src/main/java/com/dotori/dotori/todo/service/TodoService.java
  Server/src/main/resources/templates/index.html
  Server/src/test/java/com/dotori/dotori/service/AuthServiceTests.java
  client/app/(tabs)/explore.tsx
  client/src/user/api/authLoginApi.js
Labels: ♻️Refactor, 🔮 이소현🔮, 💡Backend

#28 ✨ Feat : Login Add
  Server/src/main/java/com/dotori/dotori/auth/controller/AuthController.java
  Server/src/main/java/com/dotori/dotori/auth/dto/AuthDTO.java
  Server/src/main/java/com/dotori/dotori/auth/jwt/TokenProvider.java
  client/app/login.js
  client/app/signup.js
  client/src/auth/api/authLoginApi.js
  client/src/auth/api/authsApi.js
  client/src/auth/hooks/useForm.js
  client/src/auth/models/Auth.js
  client/src/auth/viewmodels/useLoginViewModel.js
  client/src/auth/viewmodels/useSignUpViewModel.js
  client/src/auth/views/LoginView.js
  client/src/auth/views/SignUpView.js
  client/src/user/api/authLoginApi.js
Labels: ✨Feat, 🔮 이소현🔮, 💡Backend, 💡Frontend

#29 ✨ Feat: Post Authorize
  Server/src/main/java/com/dotori/dotori/auth/config/SecurityConfig.java
  Server/src/main/java/com/dotori/dotori/config/RootConfig.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
Labels: ✨Feat, 🧵Chore, 🦦 김신이🦦, 💡Backend

#30 ✨ Feat: Post init
  client/app/post.js
  client/src/auth/viewmodels/useLoginViewModel.js
  client/src/post/api/Postapi.js
  client/src/post/components/CommentItem.js
  client/src/post/components/CommentList.js
  client/src/post/components/PostItem.js
  client/src/post/components/PostList.js
  client/src/post/context/PostContext.js
  client/src/post/hooks/usePost.js
  client/src/post/models/Post.js
  client/src/post/viewmodels/PostViewModels.js
  client/src/post/views/PostDetailView.js
  client/src/post/views/PostListView.js
  client/src/post/views/PostViews.js
Labels: ✨Feat, 🍸조민준🍸, 💡Frontend
