Repository ToriArtis/Do-Tori, pull requests merged in 2024-08, with the labels that each got.

#31 ✨ Feat : auth Find Add
  .idea/dataSources.xml
  Server/src/main/java/com/dotori/dotori/auth/dto/AuthDTO.java
  Server/src/main/java/com/dotori/dotori/auth/entity/Auth.java
  Server/src/main/java/com/dotori/dotori/auth/service/AuthService.java
  client/app/emailFind.js
  client/app/passwordFind.js
  client/src/auth/api/authLoginApi.js
  client/src/auth/api/authsApi.js
  client/src/auth/viewmodels/useEmailFindViewModel.js
  client/src/auth/viewmodels/usePasswordFindViewModel.js
  client/src/auth/views/DeleteView.js
  client/src/auth/views/EmailFindView.js
  client/src/auth/views/LoginView.js
  client/src/auth/views/PasswordFindView.js
  client/src/auth/views/SignUpView.js
  client/tsconfig.json
Labels: ✨Feat, 🔮 이소현🔮, 💡Backend, 💡Frontend

#32 ✨ Feat : profile + settings Add
  client/app/profile.js
  client/app/setting.js
  client/src/auth/api/authLoginApi.js
  client/src/auth/viewmodels/useProfileViewModel.js
  client/src/auth/views/ProfileView.js
  client/src/auth/views/SettingView.js
Labels: ✨Feat, 🔮 이소현🔮, 💡Frontend

#33 ✨Feat: Post + Auth TestData
  Server/src/main/java/com/dotori/dotori/auth/config/SecurityConfig.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/test/DataInitializer.java
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
Labels: ✨Feat, 🧵Chore, 🦦 김신이🦦, 💡Backend

#34 ✨feat: Next.js init
  Client-Next/.eslintrc.json
  Client-Next/.gitignore
  Client-Next/README.md
  Client-Next/jsconfig.json
  Client-Next/next.config.mjs
  Client-Next/package-lock.json
  Client-Next/package.json
  Client-Next/postcss.config.mjs
  Client-Next/public/next.svg
  Client-Next/public/vercel.svg
  Client-Next/src/app/favicon.ico
  Client-Next/src/app/globals.css
  Client-Next/src/app/layout.js
  Client-Next/src/app/page.js
  Client-Next/tailwind.config.js
Labels: ✨Feat, 🍸조민준🍸, 💡Frontend

#35 ✨feat: Next foldering
  Client-Next/src/auth/api/a
  Client-Next/src/auth/components/a
  Client-Next/src/auth/hooks/a
  Client-Next/src/auth/models/a
  Client-Next/src/auth/viewmodels/a
  Client-Next/src/auth/views/a
  Client-Next/src/common/components/a
  Client-Next/src/common/hooks/a
  Client-Next/src/post/api/a
  Client-Next/src/post/components/a
  Client-Next/src/post/hooks/a
  Client-Next/src/post/models/a
  Client-Next/src/post/viewmodels/a
  Client-Next/src/post/views/a
  Client-Next/src/todo/api/a
  Client-Next/src/todo/components/a
  Client-Next/src/todo/hooks/a
  Client-Next/src/todo/models/a
  Client-Next/src/todo/viewmodels/a
  Client-Next/src/todo/views/a
Labels: ✨Feat, 🍸조민준🍸, 💡Frontend

#37 ✨ Feat: posts list add
  Client-Next/README.md
  Client-Next/pages/posts.js
  Client-Next/src/post/api/a
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/a
  Client-Next/src/post/components/popularPosts.js
  Client-Next/src/post/components/postCreateBox.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/components/postList.js
  Client-Next/src/post/hooks/a
  Client-Next/src/post/models/a
  Client-Next/src/post/models/post.js
  Client-Next/src/post/viewmodels/a
  Client-Next/src/post/viewmodels/postViewModel.js
  Client-Next/src/post/views/a
  Client-Next/src/post/views/postListView.js
Labels: ✨Feat, 🍸조민준🍸, 💡Frontend

#38 🐛 Fix: config, postservice
  Server/src/main/java/com/dotori/dotori/auth/config/SecurityConfig.java
  Server/src/main/java/com/dotori/dotori/auth/config/WebMVCConfig.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 🍸조민준🍸, 💡Backend

#39 ✨feat: todo 기능 추가
  Client-Next/package-lock.json
  Client-Next/package.json
  Client-Next/pages/index.js
  Client-Next/pages/todo.js
  Client-Next/src/app/favicon.ico
  Client-Next/src/app/globals.css
  Client-Next/src/app/layout.js
  Client-Next/src/app/page.js
  Client-Next/src/auth/components/css/users.module.css
  Client-Next/src/auth/views/LoginView.js
  Client-Next/src/todo/api/a
  Client-Next/src/todo/components/AddTodo.js
  Client-Next/src/todo/components/a
  Client-Next/src/todo/components/todo.js
  Client-Next/src/todo/hooks/a
  Client-Next/src/todo/models/a
  Client-Next/src/todo/models/todoModels.js
  Client-Next/src/todo/viewmodels/a
  Client-Next/src/todo/viewmodels/todoViewModels.js
  Client-Next/src/todo/views/a
  Server/src/main/java/com/dotori/dotori/config/RootConfig.java
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
  Server/src/main/java/com/dotori/dotori/todo/dto/TodoDTO.java
  Server/src/main/java/com/dotori/dotori/todo/entity/Todo.java
  Server/src/main/java/com/dotori/dotori/todo/service/TodoService.java
Labels: 🐛bug, 📝Docs, 👻Etc, ✨Feat, 👻help wanted, ♻️Refactor, 🥕 채현영🥕, 💡Backend, 💡Frontend

#44 ♻️ Refactor : app
  .idea/compiler.xml
  Client-Next/package-lock.json
  Client-Next/package.json
  Client-Next/src/app/globals.css
  Client-Next/src/app/layout.js
  Client-Next/src/app/page.js
  Client-Next/src/auth/api/authApi.js
  Client-Next/src/auth/api/authLoginApi.js
  Client-Next/src/auth/components/css/users.css
  Client-Next/src/auth/views/LoginView.js
  Server/src/main/java/com/dotori/dotori/auth/controller/AuthController.java
  Server/src/main/java/com/dotori/dotori/auth/service/AuthService.java
Labels: ♻️Refactor, 🔮 이소현🔮, 💡Backend, 💡Frontend

#45 ✨ Feat: Post add, get postlist
  Client-Next/README.md
  Client-Next/package-lock.json
  Client-Next/package.json
  Client-Next/pages/_document.js
  Client-Next/src/common/components/a
  Client-Next/src/common/hooks/a
  Client-Next/src/components/Sidebar.js
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/popularPosts.js
  Client-Next/src/post/components/postCreateBox.js
  Client-Next/src/post/components/postList.js
  Client-Next/src/post/views/postListView.js
  Client-Next/tailwind.config.js
Labels: ✨Feat, 🍸조민준🍸, 💡Frontend

#46 🐛 Fix: Postadd to requestparam, content null check
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 🍸조민준🍸, 💡Backend

#47 🐛fix: todo CRUD 버그 수정
  Client-Next/package-lock.json
  Client-Next/package.json
  Client-Next/pages/todo.js
  Client-Next/src/todo/components/AddTodo.js
  Client-Next/src/todo/components/Calendar.js
  Client-Next/src/todo/components/todo.js
  Client-Next/src/todo/models/todoModels.js
  Client-Next/src/todo/viewmodels/todoViewModels.js
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
  Server/src/main/java/com/dotori/dotori/todo/service/TodoService.java
Labels: 🐛bug, ✨Feat, 💡Backend, 💡Frontend

#48 ✨ Feat: Sidebar, like, bookmark, etc..
  Client-Next/README.md
  Client-Next/contexts/ThemeContext.js
  Client-Next/pages/_app.js
  Client-Next/pages/_document.js
  Client-Next/src/components/Sidebar.js
  Client-Next/src/components/ThemeContext.js
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/postCreateBox.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/views/postListView.js
Labels: ✨Feat, 🍸조민준🍸, 💡Frontend

#49 ✨feat: todo calendar 기능 추가
  Client-Next/pages/todo.js
  Client-Next/src/todo/components/AddTodo.js
  Client-Next/src/todo/components/Calendar.js
  Client-Next/src/todo/components/css/Calendar.module.css
  Client-Next/src/todo/components/todo.js
  Client-Next/src/todo/viewmodels/todoViewModels.js
Labels: ✨Feat, 👻help wanted, 🥕 채현영🥕, 💡Backend, 💡Frontend

#50 🐛fix: Post, Comment , Reply, HotPost fix
  Client-Next/README.md
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/popularPosts.js
  Client-Next/src/post/components/postCreateBox.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/views/postListView.js
  Server/src/main/java/com/dotori/dotori/auth/config/SecurityConfig.java
  Server/src/main/java/com/dotori/dotori/auth/entity/Auth.java
  Server/src/main/java/com/dotori/dotori/config/WebConfig.java
  Server/src/main/java/com/dotori/dotori/post/controller/ImageController.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/CommentDTO.java
  Server/src/main/java/com/dotori/dotori/post/entity/Post.java
  Server/src/main/java/com/dotori/dotori/post/repository/BookmarkRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/ToriBoxRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
  client/app/post-create.js
  client/app/post-detail.js
  client/app/post-edit.js
  client/app/post-list.js
  client/src/post/components/PopularPosts.js
  client/src/post/components/PostCreateBox.js
  client/src/post/components/PostItem.js
  client/src/post/views/PostCreateView.js
  client/src/post/views/PostDetailView.js
  client/src/post/views/PostEditView.js
  client/src/post/views/PostListView.js
Labels: 🐛bug, ✨Feat, 💄Style, 🍸조민준🍸, 💡Frontend

#51 🐛 Fix: post service, controller, db cascade, authemail to unique
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
Labels: 🐛bug, 🍸조민준🍸, 💡Backend

#52 🐛 Fix: image rendering, uploading fix
  Client-Next/README.md
  Client-Next/src/post/components/postItem.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸, 💡Frontend

#53 🐛 Fix: image bug - config, service
  Server/src/main/java/com/dotori/dotori/auth/config/SecurityConfig.java
  Server/src/main/java/com/dotori/dotori/config/WebConfig.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 🍸조민준🍸, 💡Backend

#56 🐛 Fix: Post Fix
  Server/src/main/java/com/dotori/dotori/auth/controller/AuthController.java
  Server/src/main/java/com/dotori/dotori/auth/dto/AuthDTO.java
  Server/src/main/java/com/dotori/dotori/config/RootConfig.java
  Server/src/main/java/com/dotori/dotori/post/controller/ImageController.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/CommentDTO.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostDTO.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostListCommentCountDTO.java
  Server/src/main/java/com/dotori/dotori/post/entity/Bookmark.java
  Server/src/main/java/com/dotori/dotori/post/entity/Comment.java
  Server/src/main/java/com/dotori/dotori/post/entity/Post.java
  Server/src/main/java/com/dotori/dotori/post/entity/ToriBox.java
  Server/src/main/java/com/dotori/dotori/post/repository/BookmarkRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/CommentRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/PostRepository.java
  Server/src/main/java/com/dotori/dotori/post/repository/ToriBoxRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostLikeService.java
  Server/src/main/java/com/dotori/dotori/post/service/PostSearchImpl.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 🦦 김신이🦦, 💡Backend

#57 🐛Fix: Auth Login Error Fix + Post Comment + ModifyImage + Like + Bookmark ...
  Client-Next/package-lock.json
  Client-Next/package.json
  Client-Next/src/auth/api/authLoginApi.js
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/popularPosts.js
  Client-Next/src/post/components/postCreateBox.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/components/postList.js
  Client-Next/src/post/models/post.js
  Client-Next/src/post/views/postListView.js
Labels: 🐛bug, 👻Etc, ✨Feat, 🦦 김신이🦦, 💡Frontend

#58 ✨Feat: Post Search
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/views/postListView.js
Labels: 🐛bug, ✨Feat, 🦦 김신이🦦, 💡Frontend

#63 🐛Fix: addPost Fix
  Server/src/main/java/com/dotori/dotori/auth/controller/AuthController.java
  Server/src/main/java/com/dotori/dotori/post/controller/ImageController.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/CommentDTO.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostListCommentCountDTO.java
  Server/src/main/java/com/dotori/dotori/post/entity/ToriBox.java
  Server/src/main/java/com/dotori/dotori/post/repository/CommentRepository.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 🧵Chore, 🦦 김신이🦦, 💡Backend

#64 ✨Feat: Following Post List
  Client-Next/src/post/components/postList.js
Labels: 🐛bug, 👻Etc, ✨Feat, 🦦 김신이🦦

#65 ✨Feat: Following Post List
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/postCreateBox.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/components/postList.js
  Client-Next/src/post/models/post.js
  Client-Next/src/post/views/postListView.js
Labels: 🐛bug, 👻Etc, ✨Feat, 🦦 김신이🦦, 💡Frontend

#66 🐛Fix: post file fix
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/views/postListView.js
Labels: 🐛bug, 🦦 김신이🦦, 💡Frontend

#67 🐛Fix: Comment More Button Fix
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/postItem.js
Labels: 🐛bug, 🦦 김신이🦦, 💡Frontend

#69 ✨Feat: Post Mention Front
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/postCreateBox.js
Labels: ✨Feat, 🦦 김신이🦦, 💡Frontend

#74 ♻️Refactor: Post Hooks
  Client-Next/package-lock.json
  Client-Next/package.json
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/hooks/usePostItem.js
  Client-Next/src/post/views/postListView.js
  Client-Next/src/post_front.zip
Labels: 🐛bug, ♻️Refactor, 🦦 김신이🦦, 💡Frontend

#75 🐛Fix: Post Search Fix
  Server/src/main/java/com/dotori/dotori/post/dto/PostListCommentCountDTO.java
  Server/src/main/java/com/dotori/dotori/post/service/PostSearchImpl.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 🦦 김신이🦦, 💡Backend

#76 ⚡️ Feat: toribox init
  Client-Next/README.md
  Client-Next/pages/bookmark.js
  Client-Next/pages/toribox.js
  Client-Next/src/auth/views/proFileView.js
  Client-Next/src/components/Sidebar.js
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/views/LikedPostsView.js
  Client-Next/src/post/views/bookmarkView.js
  Client-Next/src/post/views/toriboxView.js
Labels: ✨Feat, 🍸조민준🍸, 💡Frontend

#79 📌test: repo 테스트 코드 수정
  .gitignore
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
  Server/src/test/java/com/dotori/dotori/repository/AuthRepositoryTests.java
  Server/src/test/java/com/dotori/dotori/repository/CommentRepositoryTests.java
  Server/src/test/java/com/dotori/dotori/repository/PostRepositoryTests.java
  Server/src/test/java/com/dotori/dotori/repository/TodoRepositoryTests.java
  Server/src/test/java/com/dotori/dotori/repository/ToriBoxRepositoryTests.java
Labels: 📌Test, 🥕 채현영🥕, 💡Backend

#80 🧱build: 깃이그노어 설정 완료~!
  Client-Next/src/Config.js
  Server/src/main/resources/application.properties
  Server/src/main/resources/static/images/1717432841409_71835_craw1.jpg
  Server/src/main/resources/static/images/1723353106921_피그마.png
  Server/src/main/resources/static/images/1723353107030_사파리.png
  Server/src/main/resources/static/images/1723353283538_사파리.png
  Server/src/main/resources/static/images/1723353283596_크롬.png
  Server/src/main/resources/static/images/1723353810168_크롬.png
  Server/src/main/resources/static/images/1723358219171_googlelogo_color_92x30dp.png
  Server/src/main/resources/static/images/1723361261102_피그마.png
  Server/src/main/resources/static/images/1723361304916_피그마.png
  Server/src/main/resources/static/images/1723361348809_사람.png
  Server/src/main/resources/static/images/1723361405335_투두리스트.PNG
  Server/src/main/resources/static/images/1723361632219_피그마.png
  Server/src/main/resources/static/images/1723361698439_1-1. AUTH_회원가입.png
  Server/src/main/resources/static/images/1723361698503_사파리.png
  Server/src/main/resources/static/images/1723361780501_사람.png
  Server/src/main/resources/static/images/1723361780549_1. AUTH_로그인.png
  Server/src/main/resources/static/images/1723362554523_엣지마지막.png
  Server/src/main/resources/static/images/1723362554573_크롬.png
  Server/src/main/resources/static/images/1723363232835_MYPage (2).png
  Server/src/main/resources/static/images/1723363232939_피그마.png
  Server/src/main/resources/static/images/g-logo.png
  Server/src/main/resources/static/images/naverlogin.png
  client/expo-env.d.ts
Labels: 🧵Chore, 🥕 채현영🥕

#82 🐛Fix: Post Mention..
  Server/src/main/java/com/dotori/dotori/auth/dto/AuthDTO.java
  Server/src/main/java/com/dotori/dotori/auth/service/AuthService.java
  Server/src/main/java/com/dotori/dotori/follow/controller/FollowController.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/dto/PostDTO.java
  Server/src/main/java/com/dotori/dotori/post/entity/Post.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 🦦 김신이🦦, 💡Backend

#83 ♻️Refactor: Post CSS Refactor
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/css/popularPosts.css
  Client-Next/src/post/components/css/postCreateBox.css
  Client-Next/src/post/components/css/postItem.css
  Client-Next/src/post/components/css/postList.css
  Client-Next/src/post/components/popularPosts.js
  Client-Next/src/post/components/postCreateBox.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/components/postList.js
  Client-Next/src/post/views/css/postListView.css
  Client-Next/src/post/views/postListView.js
Labels: ♻️Refactor, 🦦 김신이🦦, 💡Frontend

#84 🐛Fix: ToriBox Fix
  Client-Next/package-lock.json
  Client-Next/package.json
  Client-Next/src/post/components/postList.js
Labels: 🐛bug, 🦦 김신이🦦, 💡Frontend

#85 💄Style: Post List CSS
  Client-Next/src/post/components/css/popularPosts.css
  Client-Next/src/post/components/css/postCreateBox.css
  Client-Next/src/post/components/css/postDetailPage.css
  Client-Next/src/post/components/css/postItem.css
  Client-Next/src/post/components/popularPosts.js
  Client-Next/src/post/components/postCreateBox.js
  Client-Next/src/post/components/postDetailPage.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/views/css/postListView.css
  Client-Next/src/post/views/postListView.js
Labels: 💄Style, 🦦 김신이🦦, 💡Frontend

#88 🐛Fix: Post Modify, Delete Fix
  Server/src/main/java/com/dotori/dotori/auth/service/AuthService.java
  Server/src/main/java/com/dotori/dotori/post/controller/PostController.java
  Server/src/main/java/com/dotori/dotori/post/service/PostService.java
Labels: 🐛bug, 🦦 김신이🦦, 💡Backend

#89 ✨Feat: Post Detail Page
  Client-Next/pages/post/[pid].js
  Client-Next/src/auth/api/authLoginApi.js
  Client-Next/src/auth/utils/auth.js
  Client-Next/src/post/api/postApi.js
  Client-Next/src/post/components/css/postDetailPage.css
  Client-Next/src/post/components/css/postItem.css
  Client-Next/src/post/components/popularPosts.js
  Client-Next/src/post/components/postDetailPage.js
  Client-Next/src/post/components/postItem.js
  Client-Next/src/post/hooks/usePostItem.js
  Client-Next/src/post/views/postListView.js
Labels: 🐛bug, ✨Feat, 💡Frontend

#90 🐛fix: todo Categori filtering
  .vscode/settings.json
  Client-Next/pages/todo.js
  Client-Next/src/todo/viewmodels/todoViewModels.js
  Server/src/main/java/com/dotori/dotori/auth/dto/AuthDTO.java
  Server/src/main/java/com/dotori/dotori/todo/controller/TodoController.java
  Server/src/test/java/com/dotori/dotori/repository/ToriBoxRepositoryTests.java
  Server/src/test/java/com/dotori/dotori/service/AuthServiceTests.java
  Server/src/test/java/com/dotori/dotori/service/CommentServiceTests.java
  Server/src/test/java/com/dotori/dotori/service/PostServiceTests.java
  Server/src/test/java/com/dotori/dotori/service/TodoServiceTests.java
Labels: 🐛bug, 👻help wanted, 📌Test, 🥕 채현영🥕, 💡Backend, 💡Frontend
